### ISSUE TITLE
Add new competitors

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-live#7] opened 2019-09-22 12:32 UTC
If there is on-site registrations, the process of adding new competitors is very tricky:

1. Go to WCA Website to create confirmed registration
2. Synchronize
3. Add new competitors to events if rounds already opened

At first to create registrations we need to be an organizer or a delegate of this competition. But often score-takers is another people, organizers and delegates are busy at another tasks. Provide to score-takers opened WCA account of organizer or (especially) a delegate is not secure. Maybe worth to make some 'adding menu' to WCA Live?
At second maybe it's good idea to assign new competitors to already opened rounds?

**Comment by jonatanklosko** [comment] 2019-09-22 12:43
WCA Live links to a dedicated form on the WCA website when you can enter all necessary data of the new person, then you just need to synchronize, we intentionally use the WCA website here to have a single source of registrations. We actually think that plain score-takers should have limited access to just do dataentry and changes to schedule/events/competitors should be done via the WCA website by either the delegate or organizer (if someone is trusted and meant to perform this kind of tasks, he should most likely be marked as an organizer as well). People are used to scoretakers having a lot of permissions given how Cubecomps operates, but if you think about it, scoretakers should just take the scores as the name suggests ^^
Adding new competitors to existing rounds is already implemented, on the admin round view there is an "Add competitor" icon that allows you to select whoever you want.
I think at this point this functionality works as intended to, we may revisit this flow in the future though.

Related discussion [here](https://docs.google.com/document/d/18OLajbUZ1C_NPvI_geO8oX0rV2aWjxkETGsWwSh53r4/edit).

**Closed as completed by jonatanklosko** 2019-09-22 12:43 UTC

**Comment by viroulep** [comment] 2019-09-22 21:59
>Provide to score-takers opened WCA account of organizer or (especially) a delegate is not secure.

Yes definitely!
Please never do that :)
