### ISSUE TITLE
Show Championship Podium On Podium Page

### ISSUE THREAD

**Issue by simonkellly** [thewca/wca-live#120] opened 2022-10-31 01:32 UTC
It would be great to have a way to see the championship podiums as well as the normal podium on the podium page, which would save from having to manually work out winners when calling out awards, or even just having a normal look at the results.

**Comment by jonatanklosko** [comment] 2022-10-31 01:41
Duplicate of #36 :)

**Closed as completed by jonatanklosko** 2022-10-31 01:41 UTC
