### ISSUE TITLE
Fuzzy search for competitions

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-live#38] opened 2019-11-10 16:16 UTC
It was not an issue at first, but now that we have a whole lot of competitions there it could be very nice to have a "search" field to filter displayed competitions.

**Comment by jonatanklosko** [comment] 2019-11-11 10:30
Duplicate of #24 =)

**Closed as completed by jonatanklosko** 2019-11-11 10:30 UTC
Labels: duplicate

**Comment by viroulep** [comment] 2019-11-11 10:37
Looks like I can't properly search through a dozen of issues...
