### ISSUE TITLE
Personal Record marker incorrectly assigned 

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-live#207] opened 2024-01-31 02:40 UTC
Report from Wilson Li:

> At SacCubing XVI 2024, I had an average result of 34.00 for Square-1, which was not a PR at the time. However, WCA Live indicated it as so. When results were posted, the average was correctly indicated as a non-PR result. See attached screenshots.

![image](https://github.com/thewca/wca-live/assets/52967253/ebcfc125-5e94-4947-b56f-fe7ed35ae1f9)

**Comment by jonatanklosko** [comment] 2024-01-31 04:50
Most likely a duplicate of #145.

**Closed as completed by jonatanklosko** 2024-01-31 04:50 UTC

**Comment by jonatanklosko** [comment] 2024-01-31 05:16
The previous average PR for that person comes from a competition, which results had been posted just 4 days before that one, so the wrong record marker would be expected if there was no sync between the results were posted and the sq1 round.
